import "./globals.css";

// Own Components
import Navbar from "./components/navbar/navbar";
import Head from "next/head";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="">
          <Navbar></Navbar>
        </div>
        <div>{children}</div>
      </body>
    </html>
  );
}
